version: 2
project_name: jacked

env:
  - CGO_ENABLED=0

git:
  ignore_tags:
    - "nightly"

release:
  github:
    owner: carbonetes
    name: jacked
  name_template: 'Jacked {{ .Tag }}'
  draft: false
  prerelease: auto

before:
  hooks:
    - go mod tidy
    - go test -timeout=5m ./...

builds:
  - id: jacked
    binary: jacked
    main: ./cmd/jacked/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"  # macOS doesn't support 32-bit
      - goos: linux  
        goarch: "386"  # Skip 32-bit Linux to keep builds focused
      - goos: windows
        goarch: "386"  # Skip 32-bit Windows due to SQLite compatibility issues
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/carbonetes/jacked/cmd/jacked/build.version={{.Version}}
      - -X github.com/carbonetes/jacked/cmd/jacked/build.buildDate={{.Date}}
      - -X github.com/carbonetes/jacked/cmd/jacked/build.gitCommit={{.FullCommit}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE

universal_binaries:
  - id: jacked-universal
    ids:
      - jacked
    name_template: 'jacked'
    replace: true

nfpms:
  - id: default
    file_name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    package_name: jacked
    vendor: Carbonetes
    homepage: https://github.com/carbonetes/jacked
    maintainer: Carbonetes Engineering <eng@carbonetes.com>
    description: Comprehensive vulnerability scanner for container images and filesystems
    license: Apache-2.0
    formats:
      - rpm
      - deb
      - apk
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/jacked/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/jacked/README.md

brews:
  - repository:
      owner: carbonetes
      name: homebrew-jacked
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    ids:
      - default
    commit_author:
      name: Carbonetes Bot
      email: eng@carbonetes.com
    homepage: https://www.carbonetes.com/
    description: "Comprehensive vulnerability scanner for container images and filesystems"
    license: "Apache-2.0"

scoops:
  - repository:
      owner: carbonetes
      name: jacked-bucket
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: Carbonetes Bot
      email: eng@carbonetes.com
    homepage: https://www.carbonetes.com/
    description: "Comprehensive vulnerability scanner for container images and filesystems"
    license: "Apache-2.0"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
