# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        check-latest: true
        cache: true

    - run: go mod tidy

    - name: Unit Tests
      run: |
        cd test
        go clean -testcache
        go test -v ./...
        
    - name: Runtime Test
      run: go run .

    - name: Build Test
      run: go build .
