name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read
  
jobs:
  Lint-Check:
    name: Lint Checks
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          skip-pkg-cache: true

  Unit-Tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        check-latest: true
        cache: true

    - run: go mod tidy

    - name: Unit Tests
      run: |
        cd test
        go clean -testcache
        go test -v ./...
        
    - name: Runtime Test
      run: go run .

    - name: Build Test
      run: go build .
